version: "3"
services:
  nest:
    image: nest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - .env:/app/.env
    depends_on:
      - db

  nginx:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=_
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80

  db:
    image: mariadb:10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:

